version: '2.3'

volumes:
  data1-1:
  clickhouse:

services:
  minio:
    extends:
      file: minio-service.yml
      service: minio

  minio-client:
    extends:
      file: minio-client.yml
      service: minio-client
    depends_on:
      minio:
        condition: service_healthy

  clickhouse1:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    user: clickhouse:clickhouse
    container_name: clickhouse1
    hostname: clickhouse1
    depends_on:
      minio-client:
        condition: service_healthy

  qryn:
    extends:
      file: qryn.yml
      service: qryn
    container_name: qryn
    depends_on:
      clickhouse1:
        condition: service_healthy
